apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: tethys
data:
  AWS_REGION: "us-east-1"
  S3_BUCKET: "tethys-dev-files-4acaaa0c"
  MAX_TTL_SECONDS: "604800"
  VAULT_ADDR: ":8080"
