apiVersion: v1
kind: ServiceAccount
metadata:
  name: wiper
  namespace: tethys
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::<account>:role/tethys-dev-wiper
automountServiceAccountToken: false
